### ISSUE TITLE
Cannot choose working directory on Kubuntu 20.04

### ISSUE THREAD

**Issue by HayashiEsme** [quickgui/quickgui#22]
On selecting the [...] button, this error prints out to a terminal listening to desktop environment logs 

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/file_picker_linux.dart:95)
<asynchronous suspension>
#2      FilePickerLinux.getDirectoryPath (package:file_picker/src/file_picker_linux.dart:55)
<asynchronous suspension>
#3      _ManagerState._buildVmList.<anonymous closure> (package:quickgui/src/pages/manager.dart:164)
<asynchronous suspension>

```

This was already [triaged and solved in the discord channel](https://discord.com/channels/712850672223125565/739446818252783647/909511251724496967), and the solution here is to install the missing dependency like so:
`sudo apt install zenity `

**Comment by ymauray** [comment]
Thanks, this will - should - be fixed in the next release which should land soon.

**Comment by ymauray** [comment]
That should be fixed now : 

```shell
$ sudo apt info quickgui
Package: quickgui
Version: 1.1.5-1~hirsute1.0
Depends: zenity
...
```
